# My variables
name: Lei Zhang
description: Personal blog and portfolio of Lei Zhang
url: https://www.leizhang.ai
google_verification: null


# Plugins
plugins:
  - jekyll-sitemap


# Permalinks
permalink: /:title/


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "_posts/archive", "Gemfile", "Gemfile.lock"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
